"""3_day.0

Revision ID: ca57c72729d9
Revises: ca75369de92c
Create Date: 2022-06-08 14:57:23.924965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca57c72729d9'
down_revision = 'ca75369de92c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
